### ISSUE TITLE
Typing command with no args produces error

### ISSUE THREAD

**Issue by tadhgboyle** [Turbotailz/slack-alphabetise#1]
<img width="1093" alt="Screen Shot 2021-03-24 at 10 58 07 PM" src="https://user-images.githubusercontent.com/26070412/112426020-676c6d00-8cf4-11eb-8b99-dd84ab753428.png">

**Comment by Turbotailz** [comment]
Improved in v1.0.3

![image](https://user-images.githubusercontent.com/10846855/112743962-adbd1700-8fe7-11eb-89ed-0897a1c4ef72.png)
