### ISSUE TITLE
Typing invalid character produces error

### ISSUE THREAD

**Issue by tadhgboyle** [Turbotailz/slack-alphabetise#2]
<img width="1042" alt="Screen Shot 2021-03-24 at 10 58 51 PM" src="https://user-images.githubusercontent.com/26070412/112426067-810db480-8cf4-11eb-97b4-0af7e28c040e.png">

**Comment by Turbotailz** [comment]
Improved in v.1.0.3

![image](https://user-images.githubusercontent.com/10846855/112743956-98e08380-8fe7-11eb-98e4-d9d89e08b785.png)
