### ISSUE TITLE
Typing invalid style produces error

### ISSUE THREAD

**Issue by tadhgboyle** [Turbotailz/slack-alphabetise#3]
<img width="1112" alt="Screen Shot 2021-03-24 at 10 59 39 PM" src="https://user-images.githubusercontent.com/26070412/112426130-9da9ec80-8cf4-11eb-8fcb-9b39ac74fae2.png">

**Comment by Turbotailz** [comment]
Improved in v1.0.3
![image](https://user-images.githubusercontent.com/10846855/112743924-5c148c80-8fe7-11eb-90a1-b34d71227bca.png)
